name=PixelPlanner
version=0.0.1
author=PowerBroker2 <gitstuff2@gmail.com>
maintainer=PowerBroker2 <gitstuff2@gmail.com>
sentence=Arduino library to make it easy to compose display frame buffers for TFTs like the ILI9341
paragraph=Arduino library to make it easy to compose display frame buffers for TFTs like the ILI9341
category=Display
url=https://github.com/PowerBroker2/PixelPlanner
architectures=*
